[package]
name = "verifx_cli"
version = "0.1.0"
edition = "2021"

[dependencies]

clap="3.0"
solana-client="1.10"
solana-sdk="1.10"
sha2="0.10"
skim="0.10"
walkdir="2"
colored="2"
indicatif="0.17"
tokio={version="1", features=["full"]}
borsh="0.9"


